server:
  port: ${PORT:8761}

spring:
  application:
    name: service-discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${base-url:http://localhost:8761}/eureka


management:
  endpoints:
    web:
      exposure:
        include: '*'